name: openjdk11

on:
  workflow_dispatch:
    inputs:
      tag:   
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./openJDK/11/jre/alpine_cn
          platforms: linux/amd64,linux/arm64
          push: true
          tags: midaug/openjdk11:jre-latest,midaug/openjdk11:jre-${{ github.event.inputs.tag }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./openJDK/11/jdk/alpine_cn
          platforms: linux/amd64,linux/arm64
          push: true
          tags: midaug/openjdk11:jdk-latest,midaug/openjdk11:latest,midaug/openjdk11:jdk-${{ github.event.inputs.tag }}          
